repo: 'lists-n-grids'
canvasCourse: 'web-dev-2'

inherit:
  - naming-restrict-live
  - git-2
  - html
  - css
  - gridifier
  - typografier
  - css-order-grid-type-main
  - google-fonts
  - img-flex
  - screenshots-all

html:
  - path: 'index.html'
    has:
      - ['link[href*="Denk+One"]', 'The font, `Denk One`, from Google Fonts should be included']
      - 'a[href*="https://en.wikipedia.org/wiki/"]'
      - 'main'
      - 'main > h1'
      - 'main > ol'
      - 'li > div'
      - 'li img'
      - 'li h2'
      - 'li p'
      - 'li a'
      - '.card'
    search:
      - 'Prehistoric mammals'
      - 'Arsinoitherium'
      - 'Elasmotherium'
      - 'Glyptodon'
      - 'Megatherium'
      - 'Learn more about'
      - 'grid-stretch'
      - 'content-fill'
      - 'unit-content-distribute'

css:
  - path: 'css/main.css'
    locked: true
  - path: 'css/grid.css'
    locked: true
  - path: 'css/type.css'
    locked: true
